### PR TITLE
Fix the name of the log file

### LINKED ISSUE #14: Wrong log name
The log file is erroneously called `block_store.log`, it should be `contract_meta_store.log`.

https://github.com/koinos/koinos-contract-meta-store/blob/7319269ff583b47a94ae48ba6b6f2c958a947acd/cmd/koinos-contract-meta-store/main.go#L85

### PR DESCRIPTION
**Pull request by sgerbino**
Resolves #14.

## Brief description
Changes the log name to `contract_meta_store.log`.

## Checklist

- [ ] I have built this pull request locally
- [ ] I have ran the unit tests locally
- [ ] I have manually tested this pull request
- [ ] I have reviewed my pull request
- [ ] I have added any relevant tests

### CODE REVIEW

**Review by mvandeberg — APPROVED** [review]

File: cmd/koinos-contract-meta-store/main.go [hunk 1]
```diff
@@ -82,7 +82,7 @@ func main() {
 	appID := fmt.Sprintf("%s.%s", appName, *instanceID)
 
 	// Initialize logger
-	logFilename := path.Join(util.GetAppDir(baseDir, appName), logDir, "block_store.log")
+	logFilename := path.Join(util.GetAppDir(baseDir, appName), logDir, "contract_meta_store.log")
```
Comment (mvandeberg) [inline cmd/koinos-contract-meta-store/main.go:85]: Should be `appName + ".log"`

**Review by mvandeberg — APPROVED** [review]
